Vagrant.configure("2") do |config|
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "centos7"
    vm1.vm.hostname = 'vm1'
    vm1.vm.network :public_network, ip: "192.168.0.201"
    vm1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "vm1"]
    end
  end

config.vm.define "vm2" do |vm2|
    vm2.vm.box = "centos7"
    vm2.vm.hostname = 'vm2'
    vm2.vm.network :public_network, ip: "192.168.0.202"
    vm2.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "vm2"]
    end
  end

end
