$script = <<SCRIPT
echo Installing dependencies...
sudo yum install -y unzip curl
echo Fetching Consul...
cd /tmp/
curl https://releases.hashicorp.com/consul/0.6.4/consul_0.6.4_linux_amd64.zip -o consul.zip
echo Installing Consul...
unzip consul.zip
sudo chmod +x consul
sudo mv consul /usr/bin/consul
sudo mkdir /etc/consul.d
sudo chmod a+w /etc/consul.d

curl https://releases.hashicorp.com/vault/0.5.2/vault_0.5.2_linux_amd64.zip -o vault.zip
echo Installing Vault...
unzip vault.zip
sudo chmod +x vault
sudo mv vault /usr/bin/vault
sudo mkdir /etc/vault.d
sudo chmod a+w /etc/vault.d
SCRIPT


Vagrant.configure("2") do |config|
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "centos7"
    vm1.vm.hostname = 'vm1'
    vm1.vm.network :public_network, ip: "192.168.0.201"
    vm1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "vm1"]
    end
  config.vm.provision "shell", inline: $script
  config.vm.provision "file", source: "conf.hcl", destination: "/etc/vault.d/conf.hcl"
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "centos7"
    vm2.vm.hostname = 'vm2'
    vm2.vm.network :public_network, ip: "192.168.0.202"
    vm2.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "vm2"]
    end
  config.vm.provision "shell", inline: $script
  config.vm.provision "file", source: "conf.hcl", destination: "/etc/vault.d/conf.hcl"
  end

end
